### ISSUE TITLE
toJSON

### ISSUE THREAD

**Issue by ahdinosaur** [medikoo/dbjs#6]
it would be nice to be able to call `toJSON()` on an object in the database in order to debug, test, or send over a traditional HTTP API. is this friendly for in dbjs, or is dbjs general enough that this should be in [es6-map](https://github.com/medikoo/es6-map) and [es6-set](https://github.com/medikoo/es6-set)? i'd be happy to write the code.

cheers!

**Comment by medikoo** [comment]
What was requested with that issue, will most likely be covered with https://github.com/medikoo/dbjs/issues/43
